server:
  port: 8081

spring:
    rabbitmq:
      ##springboot整合rabbitmq基本配置
      addresses: 127.0.0.1:5672
      username: tt
      password: tttm
      virtual-host: gift_monitor

      ##springboot整合rabbitmq消费者配置
      listener:
        simple:
          concurrency: 5
          max-concurrency: 10
          acknowledge-mode: manual
          prefetch: 1